### ISSUE TITLE
errors of igGeneUsage on Window and R4.2.1 /Rtool42

### ISSUE THREAD

**Issue by bmhoan** [snaketron/IgGeneUsage#12]
Hi,
I tried to test your igGeneUsage on my Windows pc, but get error below, please help me!!!
Thank you
Joan

> M <- DGU(usage.data = IGHV_HCV, # input data
+          mcmc.warmup = 250, # how many MCMC warm-ups per chain (default: 500)
+          mcmc.steps = 1000, # how many MCMC steps per chain (default: 1,500)
+          mcmc.chains = 2, # how many MCMC chain to run (default: 4)
+          mcmc.cores = 1, # how many PC cores to use? (e.g. parallel chains)
+          hdi.level = 0.95, # highest density interval level (de fault: 0.95)
+          adapt.delta = 0.95, # MCMC target acceptance rate (default: 0.95)
+          max.treedepth = 10) # tree depth evaluated at each step (default: 12)
Compiling model ... 

make cmd is
  make -f "C:/PROGRA~1/R/R-42~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-42~1.1/share/make/winshlib.mk" CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB="file6e843f2f6e5b.dll" WIN=64 TCLBIN= OBJECTS="file6e843f2f6e5b.o"

make would use
if test "zfile6e843f2f6e5b.o" != "z"; then \
  if test -e "file6e843f2f6e5b-win.def"; then \
    echo g++  -shared -s -static-libgcc -o file6e843f2f6e5b.dll file6e843f2f6e5b-win.def file6e843f2f6e5b.o  -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64" -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib"  -L"C:/PROGRA~1/R/R-42~1.1/bin/x64" -lR ; \
    g++  -shared -s -static-libgcc -o file6e843f2f6e5b.dll file6e843f2f6e5b-win.def file6e843f2f6e5b.o  -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64" -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib"  -L"C:/PROGRA~1/R/R-42~1.1/bin/x64" -lR ; \
  else \
    echo EXPORTS > tmp.def; \
    nm file6e843f2f6e5b.o | sed -n 's/^.* [BCDRT] / /p' | sed -e '/[.]refptr[.]/d' -e '/[.]weak[.]/d' | sed 's/[^ ][^ ]*/"&"/g'  >> tmp.def; \
    echo g++  -shared -s -static-libgcc -o file6e843f2f6e5b.dll tmp.def file6e843f2f6e5b.o  -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64" -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib"  -L"C:/PROGRA~1/R/R-42~1.1/bin/x64" -lR ; \
    g++  -shared -s -static-libgcc -o file6e843f2f6e5b.dll tmp.def file6e843f2f6e5b.o  -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64" -L"C:/rtools42/x86_64-w64-mingw32.static.posix/lib"  -L"C:/PROGRA~1/R/R-42~1.1/bin/x64" -lR ; \
    rm -f tmp.def; \
  fi \
fi
Error in compileCode(f, code, language = language, verbose = verbose) : 
  C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file6e843f2f6e5b.o:file6e843f2f6e5b.cpp:(.text$_ZN3tbb8internal26task_scheduler_observer_v3D0Ev[_ZN3tbb8internal26task_scheduler_observer_v3D0Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file6e843f2f6e5b.o:file6e843f2f6e5b.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x1d): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file6e843f2f6e5b.o:file6e843f2f6e5b.cpp:(.text$_ZN3tbb10interface623task_scheduler_observerD1Ev[_ZN3tbb10interface623task_scheduler_observerD1Ev]+0x3a): undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: file6e843f2f6e5b.o:file6e843f2f6e5b.cpp:(.text$_ZN3tbb10interface
In addition: Warning message:
In checkUsageData(usage.data = usage.data) :
  no replicates provided for at least one of the conditions.
Error in sink(type = "output") : invalid connection
>

**Comment by snaketron** [comment]
It looks like there is a problem with your rstan installation

Try running the following code:

```
require(rstan)
example(stan_model, package = "rstan", run.dontrun = TRUE)
```

If an error occurs then there is certainly a problem with the installation of rstan.

**Comment by snaketron** [comment]
I assume this problem was solved, issue clused.

Otherwise, please reopen.
